### ISSUE TITLE
Error while running 'learn' and 'npm test'

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/building-forms-lab#2]
@Lukeghenco @aturkewi 
I was having issues with npm test hanging. I didn't think much about it and finished the lab and just ctrl + c until all the test were passing. As you can see here:

![screen shot 2017-02-24 at 1 06 31 pm](https://cloud.githubusercontent.com/assets/16408135/23317065/8ed29f3e-fa92-11e6-9373-e7aae8d8a778.png)

In the top left tab - it is showing the running process icon which is currently hanging, however all the test passed.

When i ran 'learn' for it to update on the site i got this error.

![screen shot 2017-02-24 at 1 07 05 pm](https://cloud.githubusercontent.com/assets/16408135/23317115/aef0895c-fa92-11e6-90ca-faf7b47aaa2c.png)

It was stating that document was not defined.

My theory is perhaps the file structure of the lab? I noticed that in the "root" directory. Index.html is defined. But the index.js in src, would it be able to reference the dom that way? With it not being in the root of src?

![screen shot 2017-02-24 at 1 07 19 pm](https://cloud.githubusercontent.com/assets/16408135/23317162/d4311a74-fa92-11e6-91f6-3c30d3763cc6.png)

Just curious. I'm going to go ahead and submit this lab. But wanted to give an update that this lab may be broken as far as running the test goes.

**Comment by kwebster2** [comment]
@Lukeghenco @aturkewi 
I also had these issues. I was able to get `learn` working by moving `browser.js` out of the `helpers` folder to the `test` folder. However, `npm test` is still giving me issues.

**Comment by aturkewi** [comment]
@Enoch2k2 what happens when you run the tests in browser? Do you get any errors in the console?

**Comment by kwebster2** [comment]
@avidor @Enoch2k2 seems like the issue is with the `-w` flag in the `test` script in `package.json`. If you take away the `-w`, then `npm test` works with no issues, but `learn` doesn't work. If you add the `-R` flag, then `learn` will work, but `npm test` will not.

**Comment by Enoch2k2** [comment]
Ah, i had tried what kevin suggested and that seemed to of worked for me too. I can revert it back and try though. I didn't run the test in the browser at all. npm test i realized was working and not finishing because it was running kind of like when we used `npm run start:watch`. I didn't realize that but it was updating everytime we changed something.

When i switched the browser.js to the root dir of the test folder, i was able to run `learn` without any issues.

**Comment by kwebster2** [comment]
@avidor @Enoch2k2 seems like the issue is with the `-w` flag in the `test` script in `package.json`. If you take away the `-w`, then `npm test` works with no issues, but `learn` doesn't work. If you add the `-R` flag, then `learn` will work, but `npm test` will not.  `

**Comment by aturkewi** [comment]
@ToneLoke @jjseymour @Lukeghenco 

We may want to look at removing the `-w` (watch) for all the labs?

**Comment by aturkewi** [comment]
Removed `-w` in PR #3
