### ISSUE TITLE
User should supply the reducer

### ISSUE THREAD

**Issue by nikymorg** [learn-co-curriculum/building-forms-lab#5]
According to the Readme the user should be creating the reducer. Do you want to remove some of it to allow for that?

```
You will also need to fill in the manageBand reducer located under ./src/reducers/manageBand.js. It will need to respond to an action of type 'ADD_BAND' and correspondingly concatenate a new band each time the action is dispatched.
```

**Comment by FreeBreadsticks** [comment]
Was going to post this - the reducer is already complete when looking at the file. Perhaps some should be removed for testing/learning?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
