### ISSUE TITLE
Test 3 Not Working Correctly

### ISSUE THREAD

**Issue by itzsaga** [learn-co-curriculum/building-forms-lab#9]
According to the test, "changes the state on a keydown" yet  
`<input type='text' onKeyDown={(event) => this.handleChange(event)} />` fails  
and  
`<input type='text' onChange={(event) => this.handleChange(event)} />` passes.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
